### ISSUE TITLE
Reverse Calculation

### ISSUE THREAD

**Issue by ozkanuysal** [rodrigo-arenas/pyworkforce#35]
Hey rodrigo i have an idea,  first of all i really like to do in this library congrats.My idea is, do you think is there a chance to have Reverse erlang calculation for example when we typing agent number can we return asa,shrinkage and other parameters.Have a good day.

**Comment by rodrigo-arenas** [comment]
Hi, @ozkanuysal. Thanks for your message, I'm glad you like the library
This is already possible in the package; you can get the occupancy, service level, and the waiting probability; here are the [docs](https://pyworkforce.readthedocs.io/en/stable/api/erlangc.html) for what is required in each method.
Here is one example using one of these methods:

```python
from pyworkforce.queuing import ErlangC

erlang = ErlangC(transactions=100, asa=20/60, aht=3, interval=30, shrinkage=0.3)

erlang.service_level(positions=14)

# Returns: 0.88835
```

If you find this useful, please consider leaving a start for the package, so it can start growing :)

**Comment by rodrigo-arenas** [comment]
I'm closing this issue, let me know if you have more questions
