### ISSUE TITLE
How to handle weekly shift constraints?

### ISSUE THREAD

**Issue by nschimmoller** [rodrigo-arenas/pyworkforce#37]
Hey Rodrigo,

Thanks for this great package. Had a hopefully quick question for you. Is there a way to determine the optimal scheduling with constraints on what days of the week somebody can work. My understanding is that given inputting 7 days worth of capacity need and different shift options PyWorkforce would recommend let's say 10 people every day of the week that work the morning shift.

Obviously in the real world we can't necessarily have 10 people work all 7 days consecutively. How would we best go about finding how to optimally staff to this arrival pattern?

**Comment by rodrigo-arenas** [comment]
Hi @nschimmoller I'm glad you find this package useful
There're two ways you can approach this:

* You can set the max_resting parameter, which tells the optimizer how many days at most, a person can rest (not work at all), this is a general approach so it applies to all the people on your roast
* You can use the parameter banned_shifts, this allows you to explicitly set which days and shifts (it can be all shifts in a day for example) a particular person can't work, for example:
"banned_shifts": [{"resource": "e.johnston@randatmail.com", "shift": "Night", "day": 0}]

For a full example with both parameters check this tutorial: https://pyworkforce.readthedocs.io/en/stable/tutorials/rostering.html

**Comment by rodrigo-arenas** [comment]
I'm closing this issue, let me know if you have more questions related to this
