### ISSUE TITLE
MinAbsDifference, MinRequiredResources not working

### ISSUE THREAD

**Issue by sabdulla-ahc** [rodrigo-arenas/pyworkforce#47]
I'm unable to utilize the MinAbsDifference OR MinRequiredResources in order to calculate optimized number of call center agents per shift. After setting all the parameters, once I try to run the optimization solver, e.g: difference_solution = difference_scheduler.solve() the kernerl dies and has to be restarted. I've tried various set-ups and as little as 1 day with both MinAbsDifference and MinRequiredResources with 0 successes. It's driving me crazy, am I missing something here?? Please advise.

![Screenshot 2024-07-05 102516](https://github.com/rodrigo-arenas/pyworkforce/assets/174774002/6139059e-ecf1-4595-9734-e129701e896b)

**Comment by kostantinos-soiledis** [comment]
In anaconda enviroment, conda update --all with admin privileges in anaconda prompt solved this for me.

**Comment by rodrigo-arenas** [comment]
thanks @kostantinos-soiledis I'll put this in the installation guide
